{   'active': False,
    'application': False,
    'author': 'Marc Wimmer (marc@itewimmer.de)',
    'category': 'uncategorized',
    'css': [],
    'demo_xml': [],
    'depends': ['base', 'product'],
    'description': '',
    'installable': True,
    'js': [],
    'name': 'product_uom_helper',
    'qweb': [],
    'test': [],
    'update_xml': [],
    'version': '14.0.1.0',
    'web': False}
