{
    'active': False,
    'application': False,
    'assets': {'web.assets_qweb': []},
    'author': 'Marc Wimmer (marc@itewimmer.de)',
    'category': 'uncategorized',
    'css': [],
    'data': ['views/form.xml'],
    'demo': [],
    'demo_xml': [],
    'depends': ['base', 'product'],
    'description': '',
    'installable': True,
    'js': [],
    'name': 'product_uom_helper',
    'test': [],
    'update_xml': [],
    'version': '17.0.0.0',
    'web': False
}
